# Site settings
title: "Aspen: AI on Spark"
email: info@vital.ai
description: > # this means to ignore newlines until "baseurl:"
  Aspen provides implementations of AI algorithms on Apache Spark.
  Implementations include natural language processing and logic inferencing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aspen.vital.ai" # the base hostname & protocol for your site
twitter_username: vital_ai
github_username:  vital-ai

permalink: /blog/

# Build settings
markdown: kramdown
